baseURL = "http://localhost:1313/"
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
title = "Snow's Site"
theme = "DoIt"


[params]
# DoIt 主题版本
version = "0.4.X"
description = "This is a personal website of Snow.Z."
keywords = ["Blog", "博客", "Snow", "SlightSnow", "Snow.Z", "SnowsSite"]

[params.home.profile]
# Gravatar 邮箱, 用于优先在主页显示的头像
# gravatarEmail = "ideadsnow@gmail.com"
enable = true
avatarURL = "https://webp.slightsnow.com/avatar.jpg"
title = "Hi, here is Snow's Site."


[params.author]
name = "Snow.Z"
email = "ideadsnow@gmail.com"
link = ""
avatar = "https://webp.slightsnow.com/avatar.jpg"
gravatarEmail = ""

[params.page]
# 是否使用 lightgallery
lightgallery = true
enableLastMod = true

[params.page.toc]
# 是否使用目录
enable = true
# DoIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
keepStatic = false
# 是否使侧边目录自动折叠展开
auto = false

[params.page.code]
# 是否显示代码块的复制按钮
copy = true
maxShownLines = 50

# DoIt 新增 | 0.2.14 相关文章推荐配置
[params.page.related]
enable = true
count = 3

[params.analytics]
enable = true
# Google Analytics
[params.analytics.google]
id = "G-85J43KGENS"
# 是否匿名化用户 IP
anonymizeIP = true

[params.app]
# modern SVG favicon to use in place of older style .png and .ico files
# svgFavicon = "favicon.svg"

[params.header]
[params.header.title]
# URL of the LOGO
logo = "/favicon.png"
# title name
name = "Snow's Site"
# you can add extra information before the name (HTML format is supported), such as icons
pre = " "
# you can add extra information after the name (HTML format is supported), such as icons
post = ""
typeit = false


[menu]
[[menu.main]]
identifier = "posts"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
name = "文章"
url = "/posts/"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
weight = 1

[[menu.main]]
identifier = "tags"
pre = ""
post = ""
name = "标签"
url = "/tags/"
title = ""
weight = 2

[[menu.main]]
identifier = "categories"
pre = ""
post = ""
name = "分类"
url = "/categories/"
title = ""
weight = 3


# Hugo 解析文档的配置
[markup]
defaultMarkdownHandler = "goldmark"
# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false

# 网站地图配置
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

# Permalinks 配置
[Permalinks]
posts = "posts/:filename"
