baseURL = "http://localhost:1313/"
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
title = "Snow's 飘雪工坊"
theme = "DoIt"


[params]
# DoIt 主题版本
version = "0.4.X"
description = "Snow's 飘雪工坊"
keywords = ["Snow", "飘雪工坊", "SlightSnow", "Blog", "博客"]

[params.home.profile]
# Gravatar 邮箱, 用于优先在主页显示的头像
# gravatarEmail = "ideadsnow@gmail.com"
enable = true
avatarURL = "https://webp.slightsnow.com/avatar.jpg"
title = "你好, 我是 Snow.Z"


[params.author]
name = "Snow.Z"
email = "ideadsnow@gmail.com"
link = ""
avatar = "https://webp.slightsnow.com/avatar.jpg"
gravatarEmail = ""

[params.page]
# 是否使用 lightgallery
lightgallery = true
enableLastMod = false

[params.page.toc]
# 是否使用目录
enable = true
# DoIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
keepStatic = false
# 是否使侧边目录自动折叠展开
auto = false

[params.page.code]
# 是否显示代码块的复制按钮
copy = true
# 默认展开显示的代码行数
maxShownLines = 35
# 是否显示代码行号
lineNos = true
# 是否开启代码换行
wrap = false
# 是否显示代码块标题
header = true

# DoIt 新增 | 0.2.14 相关文章推荐配置
[params.page.related]
enable = false
count = 3

# DoIt 更改 | 0.2.0 评论系统设置
[params.page.comment]
enable = true
# DoIt 新增 | 0.2.13 giscus 评论系统设置
[params.page.comment.giscus]
enable = true
# owner/repo
dataRepo = "ideadsnow/snowsblog"
dataRepoId = "R_kgDONFSFmw"
dataCategory = "Announcements"
dataCategoryId = "DIC_kwDONFSFm84CmMuH"
dataMapping = "pathname"
dataReactionsEnabled = "1"
dataEmitMetadata = "0"
dataInputPosition = "top"
lightTheme = "light"
darkTheme = "dark"
dataLang = "zh-CN"
dataLoading = "lazy"

[params.analytics]
enable = true
# Google Analytics
[params.analytics.google]
id = "G-85J43KGENS"
# 是否匿名化用户 IP
anonymizeIP = true

[params.app]
# modern SVG favicon to use in place of older style .png and .ico files
svgFavicon = "/favicon.svg"

[params.header]
[params.header.title]
# URL of the LOGO
logo = "/favicon.svg"
# title name
name = "Snow's 飘雪工坊"
# you can add extra information before the name (HTML format is supported), such as icons
pre = " "
# you can add extra information after the name (HTML format is supported), such as icons
post = ""
typeit = false


[menu]
[[menu.main]]
identifier = "posts"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
name = "文章"
url = "/posts/"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
weight = 1

[[menu.main]]
identifier = "tags"
pre = ""
post = ""
name = "标签"
url = "/tags/"
title = ""
weight = 2

[[menu.main]]
identifier = "categories"
pre = ""
post = ""
name = "分类"
url = "/categories/"
title = ""
weight = 3


# Hugo 解析文档的配置
[markup]
defaultMarkdownHandler = "goldmark"
# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false

# 网站地图配置
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

# Permalinks 配置
[Permalinks]
posts = "posts/:filename"
